version: '3'
services:
  server:
    image: python:3.7
    restart: always
    ports:
      - '20020:8080'
    volumes:
      - .:/code
    working_dir: "/code"
    links:
      - "database:db"
    env_file:
      - config.env
    command:
      - sh
      - -c
      - |
        python -m pip install -r requirements.txt
        python main.py
  database:
    image: mariadb:10.5.10
    restart: always
    expose:
      - '3306'
    volumes:
      - "./docker/mariadb/ddl.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./docker/mariadb/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./docker/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
    env_file:
      - config.env
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci